[build]
  functions = "functions"

[template.environment]
  DAILY_API_KEY = "Replace with API key"

[[headers]]
  # Define which paths this specific [[headers]] block will cover.
  for = "/*"
    [headers.values]
    Access-Control-Allow-Origin = "*"