[build]
  functions = "functions"

[template.environment]
  DAILY_API_KEY = "change me to the key from https://dashboard.daily.co/developers"

[[headers]]
  # Define which paths this specific [[headers]] block will cover.
  for = "/*"
    [headers.values]
    Access-Control-Allow-Origin = "*"